name: Continuous Integration

on: [ push ]

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build images
        run: docker compose build

      - name: Install dependencies
        run: docker compose run app composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Check syntax
        run: docker compose run app composer syntax

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build images
        run: docker compose build

      - name: Install dependencies
        run: docker compose run app composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Execute tests
        run: docker compose run app composer test
